services:
  - type: web
    name: agentlab-streamlit
    runtime: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir --no-deps -r requirements.txt
      pip install --no-cache-dir spacy thinc  # install these with dependencies
    startCommand: streamlit run langchain.py --server.port=10000 --server.address=0.0.0.0
    envVars:
      - key: OPENAI_API_KEY
        sync: false